[package]
name = "gooseberry"
version = "0.1.0"
authors = ["Ninjani"]
edition = "2018"
description = "a knowledge base tool combining Hypothesis web annotations with an mdBook wiki"
repository = "https://github.com/out-of-cheese-error/gooseberry"
readme = "README.md"
license = "MIT"
keywords = ["knowledge-base", "hypothesis", "cli", "markdown", "wiki"]
categories = ["command-line-utilities"]

[dependencies]
# Hypothesis
# TODO: Uses the git version of hypothesis for now to make debugging quicker, remember to change this in the end
hypothesis = {default-features = false, git = "https://github.com/out-of-cheese-error/rust-hypothesis"}
tokio = { version = "0.2", features = ["macros"] }

# mdBook
mdbook = "0.3.7"
url = "2.1.1"

# CLI
structopt = "0.3.14"

# Database
sled = "0.32.0-rc1"

# Configuration management
confy = "0.4.0"
directories-next = "1.0.1"

# Error handling
eyre = "0.4.2"
color-eyre = "0.3.2"
thiserror = "1.0.19"

# Serializing
serde = "1.0.110"
serde_json = "1.0.53"
serde_derive = "1.0.110"
bincode = "1.2.1"

# Parsing and manipulating dates
chrono = { version = "0.4.11", features = ["serde"] }
chrono-english = "0.1.4"

# Fuzzy search
skim = "0.8.1"

# Console related
dialoguer = "0.6.2"
console = "0.11.3"
termimad = "0.8.23"

[profile.release]
panic = 'abort'