[package]
name = "gooseberry"
version = "0.2.0-alpha"
authors = ["Ninjani"]
edition = "2018"
description = "a knowledge base tool combining Hypothesis web annotations with an mdBook wiki"
repository = "https://github.com/out-of-cheese-error/gooseberry"
readme = "README.md"
license = "MIT"
keywords = ["knowledge-base", "hypothesis", "cli", "markdown", "wiki"]
categories = ["command-line-utilities"]
include = ["src/**/*", "README.md"]

[dependencies]
# Hypothesis
hypothesis = { version = "0.8.0", default-features = false }
tokio = { version = "1.0.2", features = ["macros"] }

# To extract the base URI
url = "2.2.0"

# CLI
structopt = "0.3.21"

# Database
sled = "0.34.6"

# Configuration management
confy = "0.4.0"
directories-next = "1.0.1"

# Error handling
eyre = "0.6.5"
color-eyre = "0.5.10"
thiserror = "1.0.23"

# Serializing
serde = "1.0.119"
serde_json = "1.0.61"
serde_derive = "1.0.119"
bincode = "1.3.1"

# Parsing and manipulating dates
chrono = { version = "0.4.19", features = ["serde"] }
chrono-english = "0.1.4"

# Fuzzy search
skim = "0.9.3"

# Console related
dialoguer = "0.7.1"
bat = { version = "0.17.1", default-features = false, features = ["regex-fancy"] }

# Indicator bar
indicatif = "0.15.0"

# Templating markdown
handlebars = "3.5.2"

[dev-dependencies]
assert_cmd = "1.0.2"
predicates = "1.0.6"
tempfile = "3.2.0"
dotenv = "0.15.0"

[profile.release]
panic = 'abort'
