[package]
name = "gooseberry"
version = "0.1.0"
authors = ["Ninjani"]
edition = "2018"
description = "a knowledge base tool combining Hypothesis web annotations with an mdBook wiki"
repository = "https://github.com/out-of-cheese-error/gooseberry"
readme = "README.md"
license = "MIT"
keywords = ["knowledge-base", "hypothesis", "cli", "markdown", "wiki"]
categories = ["command-line-utilities"]
include = ["src/**/*", "README.md"]

[dependencies]
# Hypothesis
# TODO: Uses the git version of hypothesis for now to make debugging quicker, remember to change this in the end
hypothesis = { default-features = false, git = "https://github.com/out-of-cheese-error/rust-hypothesis" }
tokio = { version = "0.2.22", features = ["macros"] }

# mdBook
mdbook = "0.4.4"
url = "2.2.0"

# CLI
structopt = "0.3.20"

# Database
sled = "0.34.4"

# Configuration management
confy = "0.4.0"
directories-next = "1.0.1"

# Error handling
eyre = "0.6.2"
color-eyre = "0.5.7"
thiserror = "1.0.22"

# Serializing
serde = "1.0.117"
serde_json = "1.0.59"
serde_derive = "1.0.117"
bincode = "1.3.1"

# Parsing and manipulating dates
chrono = { version = "0.4.19", features = ["serde"] }
chrono-english = "0.1.4"

# Fuzzy search
skim = "0.9.3"

# Console related
dialoguer = "0.7.1"
console = "0.13.0"
termimad = "0.8.29"

# Indicator bar
indicatif = "0.15.0"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"
tempfile = "3.1.0"
dotenv = "0.15.0"

[profile.release]
panic = 'abort'
